@startuml 
left to right direction

rectangle Catalogo_de_actividades{
    (Gestiona actividades comunitarias) 
    (Gestiona usuarios) 
    (Gestiona inscripciones) 
    (Gestiona materiales asignados) 
    (Verificar horas RH)
    (Inscribirse a actividad)
    (Ver actividades disponibles)
    (Registrarse)
    (Prestar material)
}

actor Admin 
Admin "1..*" --> "1..*" (Gestiona actividades comunitarias) 
Admin "1..*" --> "1..*" (Gestiona usuarios) 
Admin "1..*" --> "1..*" (Gestiona inscripciones)

actor Equipo_Operativo
Equipo_Operativo "1..*" --> "1..*" (Gestiona materiales asignados)
Equipo_Operativo "1..*" --> "1..*" (Prestar material)

actor Trabajador <<Colaborador_interno>>
Trabajador "1..*" --> "1..*" (Inscribirse a actividad)
Trabajador "1..*" --> "1..*" (Ver actividades disponibles)

actor Recursos_Humanos
Recursos_Humanos "1..*" --> "1..*" (Verificar horas RH)

actor Usuario_no_registrado
Usuario_no_registrado "1..*" --> "1..*" (Ver actividades disponibles)

Actor Usuario
Usuario "1..1" --> "1..1" (Registrarse)

(Verificar horas RH) <.. (Inscribirse a actividad) : include
(Prestar material) <.. (Inscribirse a actividad) : include

Usuario --|> Admin
Usuario --|> Equipo_Operativo
Usuario --|> Trabajador
Usuario --|> Recursos_Humanos