@startuml
class Usuario {
  -id: UUID
  +nombre: String
  +email: String
  -contraseña: String
  +tipo: String
  +codigoEmpleado: Integer
  +emailConfirmado: Boolean
  +registrarse()
  +iniciarSesion()
  #actualizarPerfil()
}

class Recursos_Humanos{
  -reportesGenerados: Int
  -ultimaRevision: DateTime
  -areaResponsable: String
  +verHorasTrabajadas():Float
  +iniciarValidacionHoras()
  +generarReporte()
}

class Trabajador{
  -departamento: String
  -puesto: String
  -horasAcumuladas: Float
  +inscribirseActividad()
  +cancelarInscripcion()
  +verActividadesDisponibles()
  +verHorasTrabajadas()
  +tomarPrestadoMaterial()
  +devolverMaterial()
}

class Equipo_Operativo{
  -areaResponsable: String
  -inventarioAsignado: String[]
  -telefonoContacto: String
  +prestarMaterial()
  +devolverMaterial()
}

class Admin{
  -ultimaConexion: DateTime
  -permisosEspeciales: String[]
  -crearUsuario()
  -eliminarUsuario()
  -modificarUsuario()
  -crearActividad()
  -eliminarActividad()
  -modificarActividad()
  -generarReporte()
  -gestionarInscripciones()
  -gestionarMateriales()
}

class Actividad {
  -id: UUID
  +titulo: String
  +id_sede: String
  +fecha: Date
  +horario: String
  +responsable: String
  -cupo: Int
  +claveTurno: String
  +semestre: String
  +activa: Boolean
  +crearActividad()
  +editarActividad()
  +eliminarActividad()
  +consultarDetalles()
  +verificarDisponibilidadHorario()
  +asignarMaterial()
  +registrarInscripcion()
  +cancelarInscripcion()
}

class Sede{
  -id: UUID
  +nombre: String
  +municipio: String
  +direccion: String
  +registrarSede()
  +actualizarDatos()
  +eliminarSede()
}

class Inscripcion {
  -id: UUID
  +estado: String
  +horas: Float
  -fechaRegistro: DateTime
  +registrarInscripcion()
  +cancelarInscripcion()
}

class Inventario{
  -id: UUID
  +nombre: String
  +descripcion: String
  +cantidadDisponible: Int
  +agregarMaterial()
  +removerMaterial()
  +actualizarCantidadDisponible()
}

class MaterialAsignado {
  -id: UUID
  +articulo: String
  +estado: String
  -fechaEntrega: DateTime
  -fechaDevolucion: DateTime
  -asignarMaterial()
  -devolverMaterial()
}

class ValidacionRH {
  -id: UUID
  +semestre: String
  -horasTotales: Float
  +fechaCierre: DateTime
  +validarHoras()
}

Usuario "1" -- "0..*" Inscripcion
Actividad "1" -right- "0..*" Inscripcion
Trabajador "0..*" -- "0..*" Actividad : participa >
Trabajador "1" -- "0..*" MaterialAsignado
Recursos_Humanos "1" -- "0..*" ValidacionRH
Sede "1" -- "0..*" Actividad
Inventario -- "0..*" MaterialAsignado
Equipo_Operativo "1" -- "0..*" MaterialAsignado
ValidacionRH "1" -- "0..*" Actividad


Usuario <|-- Recursos_Humanos
Usuario <|-- Trabajador 
Usuario <|-- Equipo_Operativo
Usuario <|-left- Admin


@enduml

